import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John Doe",
      email: "john@example.com",
      password: bcrypt.hashSync("password123"),
      isAdmin: true,
    },
    {
      name: "Jane Smith",
      email: "jane@example.com",
      password: bcrypt.hashSync("passwor3"),
      isAdmin: false,
    },
    {
      name: "Carlos Rodríguez",
      email: "carlos@example.com",
      password: bcrypt.hashSync("passwor123"),
      isAdmin: false,
    },
    {
      name: "María López",
      email: "maria@example.com",
      password: bcrypt.hashSync("password13"),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 280000,
      brand: "Nike",
      rating: 3,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
      isFeatured: true,
      banner: "/images/banner1.jpg",
      colors: ["White", "Black", "Navy"],
      sizes: ["S", "M", "L", "XL"],
    },
    {
      name: "Slim Pants",
      slug: "slim-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 360000,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 12,
      countInStock: 15,
      description: "Comfortable slim fit pants",
      isFeatured: false,
      banner: "/images/banner2.jpg",
      colors: ["Black", "Khaki", "Gray"],
      sizes: ["30", "32", "34", "36"],
    },
    {
      name: "Classic Fit Shirt",
      slug: "classic-fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 300000,
      brand: "Puma",
      rating: 4.7,
      numReviews: 10,
      countInStock: 25,
      description: "Classic style comfortable shirt",
      isFeatured: true,
      banner: "/images/banner3.jpg",
      colors: ["Blue", "White", "Pink"],
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Sports Jacket",
      slug: "sports-jacket",
      category: "Jackets",
      image: "/images/jacket1.jpg",
      price: 480000,
      brand: "Nike",
      rating: 4.8,
      numReviews: 15,
      countInStock: 10,
      description: "Lightweight sports jacket",
      isFeatured: true,
      banner: "/images/banner4.jpg",
      colors: ["Black", "Gray", "Red"],
      sizes: ["S", "M", "L", "XL"],
    },
    {
      name: "Running Shoes",
      slug: "running-shoes",
      category: "Shoes",
      image: "/images/shoes1.jpg",
      price: 600000,
      brand: "Adidas",
      rating: 4.6,
      numReviews: 20,
      countInStock: 18,
      description: "Comfortable running shoes",
      isFeatured: false,
      banner: "/images/banner5.jpg",
      colors: ["White/Blue", "Black/Red", "Gray/Green"],
      sizes: ["7", "8", "9", "10", "11", "12"],
    },
    {
      name: "Otaku Shoes",
      slug: "Otaku-shoes",
      category: "Shoes",
      image: "/images/shoes1.jpg",
      price: 30000,
      brand: "Adidas",
      rating: 4.6,
      numReviews: 20,
      countInStock: 18,
      description: "Comfortable running shoes",
      isFeatured: false,
      banner: "/images/banner5.jpg",
      colors: ["White/Blue", "Black/Red", "Gray/Green"],
      sizes: ["7", "8", "9", "10", "11", "12"],
    },
  ],
};

export default data;
